### ISSUE TITLE
Support for Quick

### ISSUE THREAD

**Issue by iampatbrown** [buildkite/test-collector-swift#11]
## 💬  Context

Quick is a popular testing framework. We should confirm the Swift Collector works with this framework. 

## 📝 Notes

- It might already work because it hooks into XCTest

## 🤝 Related

[Quick/Quick](https://github.com/Quick/Quick)

**Comment by DechengMa** [comment]
Hi @iampatbrown, I've tested and confirmed that Quick and Nimble work fine with the test collector.
<img width="1203" alt="image" src="https://github.com/buildkite/test-collector-swift/assets/30752103/a1328320-a557-4362-aa39-a32ca684f53a">
<img width="1203" alt="image" src="https://github.com/buildkite/test-collector-swift/assets/30752103/2d0825fe-9970-423e-9242-a8d1444b73fb">
I'll close this issue for now. Please feel free to reopen it if further support is needed for Quick and Nimble.
