### ISSUE TITLE
Support for Nimble

### ISSUE THREAD

**Issue by iampatbrown** [buildkite/test-collector-swift#12]
## 💬  Context

Nimble is a popular testing framework. We should confirm the Swift Collector works with this framework. 

## 📝 Notes

- It might already work because it hooks into XCTest

## 🤝 Related

[Quick/Nimble](https://github.com/Quick/Nimble)

**Comment by mokagio** [comment]
If this helps: We have various tests using Nimble in WordPress iOS.

This is the first one I found [`testCallApiWithTheSavedSlugs`](https://github.com/wordpress-mobile/WordPress-iOS/blob/a08cc72e4bfb15d4fa88c06c549c16941fb2a64a/WordPress/WordPressTest/ReaderCardServiceTests.swift#L29-L41) in the test run. With first, I mean I clicked around till I found one, not that it was prominent for any reason.

Here's screenshots of the Test Analytics page for it:

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/1218433/180196532-87b8a927-6c54-4ab4-998f-07890fad355c.png">

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/1218433/180196597-b228b62a-4ad3-48cb-8dc6-da7322a42bee.png">

**Comment by iampatbrown** [comment]
@mokagio Awesome. That's good to know. I'll give it a test drive on my end as well to get more familiar with it :)

Are you still using the collector?

Would be keen to touch base with you at some point to see how everything has been going.

**Comment by mokagio** [comment]
Howdy @iampatbrown 👋 

Yes we are still using it. I'd love to chat, but it'll have to wait till the new year.

**Comment by iampatbrown** [comment]
@mokagio Champion!! Thanks mate. Replying to what I can now :P

**Comment by DechengMa** [comment]
Hi folks, [I've tested and confirmed that Quick and Nimble work fine with the test collector](https://github.com/buildkite/test-collector-swift/issues/11#issuecomment-1942782309)
I'll close this issue for now. Please feel free to reopen it if further support is needed for Quick and Nimble.
