### ISSUE TITLE
Naming inconsistency between docs and version 0.1.0

### ISSUE THREAD

**Issue by mokagio** [buildkite/test-collector-swift#20]
Howdy 👋 

I was delighted and surprised to see Swift support in Test Analytics 🎉 🙇‍♂️ Thank you very much for that. It's not every day that I found a CI tool with early support for Apple-platform tooling.

I've been trying to setup Test Analytics in one of [our libraries](https://github.com/Automattic/Automattic-Tracks-iOS/pull/205/) at Automattic and noticed a minor issue.

## Issue

[The docs](https://buildkite.com/docs/test-analytics/swift-collectors), which I assume are code-generated from the [`README.md`](https://github.com/buildkite/test-collector-swift/blob/19e355e0115547100fc79031ec11ffcbf259fa71/README.md) say to use `BuildkiteTestCollector` as the package name, but [in version 0.1.0 the name is `BuildkiteCollector`](https://github.com/buildkite/test-collector-swift/blob/v0.1.0/Package.swift#L6).

This will result in errors along the lines of:

```
error: product 'BuildkiteTestCollector' required by package '...' target '...' not found.
```

## Proposed Solution

I think tagging a new version should be enough to solve this issue, given that [`BuildkiteTestCollector` is the current name of the package](https://github.com/buildkite/test-collector-swift/blob/19e355e0115547100fc79031ec11ffcbf259fa71/Package.swift#L6).

Thanks ✨

**Comment by iampatbrown** [comment]
Hey @mokagio! 

Thanks for bringing this up. I've just created [v0.1.1](https://github.com/buildkite/test-collector-swift/releases/tag/v0.1.1), can you confirm it's working as expected. 

Also, would love to get your feedback on the collector after you've had a chance to test it out :)

**Comment by mokagio** [comment]
Hey @iampatbrown 👋 Thank you for the super quick followup 🎖️ 

The name update worked:

<img width="835" alt="image" src="https://user-images.githubusercontent.com/1218433/173736900-e7415d42-385a-478e-84e8-190a42cafcdf.png">

However, xcodebuild failed to compile the package 🤔 

```
▸ Compiling Tracer+Live.swift
--
  |  
  | ❌  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/SourcePackages/checkouts/test-collector-swift/Sources/Core/Tracer/Tracer+Live.swift:32:38: cannot assign value of type 'Double?' to type 'TimeInterval' (aka 'Double')
  |  
  | span.duration = span.startAt.map { endAt - $0 }
  | ^~~~~~~~~~~~~~~~~~~~~~
  |  
  |  
  |  
  | ❌  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/SourcePackages/checkouts/test-collector-swift/Sources/Core/Tracer/Tracer+Live.swift:19:88: missing argument for parameter 'duration' in call
  |  
  | let span = Trace.Span(section: section, startAt: systemUptime(), detail: detail)
  | ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  |  
  |  
  | ▸ Compiling Tracer.swift
  |  
  | ❌  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/SourcePackages/checkouts/test-collector-swift/Sources/Core/Tracer/Tracer+Live.swift:32:38: cannot assign value of type 'Double?' to type 'TimeInterval' (aka 'Double')
  |  
  | span.duration = span.startAt.map { endAt - $0 }
  | ^
  |  
  |  
  |  
  | ❌  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/SourcePackages/checkouts/test-collector-swift/Sources/Core/Tracer/Tracer+Live.swift:19:88: missing argument for parameter 'duration' in call
  |  
  | let span = Trace.Span(section: section, startAt: systemUptime(), detail: detail)
  | ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  |  
  |  
  |  
  | ⚠️  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/Build/Intermediates.noindex/BuildkiteTestCollector.build/Debug-iphonesimulator/Core.build/Objects-normal/x86_64/Tracer.dia:1:1: Could not read serialized diagnostics file: error("Invalid diagnostics signature") (in target 'Core' from project 'BuildkiteTestCollector')
  |  
  | Command CompileSwift failed with a nonzero exit code
  | ^
  |  
  |  
  | ▸ Compiling UploadClient+Live.swift
  |  
  | ❌  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/SourcePackages/checkouts/test-collector-swift/Sources/Core/Tracer/Tracer+Live.swift:32:38: cannot assign value of type 'Double?' to type 'TimeInterval' (aka 'Double')
  |  
  | span.duration = span.startAt.map { endAt - $0 }
  | ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  |  
  |  
  |  
  | ❌  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/SourcePackages/checkouts/test-collector-swift/Sources/Core/Tracer/Tracer+Live.swift:19:88: missing argument for parameter 'duration' in call
  |  
  | let span = Trace.Span(section: section, startAt: systemUptime(), detail: detail)
  | ^
  |  
  |  
  |  
  | ⚠️  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/Build/Intermediates.noindex/BuildkiteTestCollector.build/Debug-iphonesimulator/Core.build/Objects-normal/x86_64/UploadClient+Live.dia:1:1: Could not read serialized diagnostics file: error("Invalid diagnostics signature") (in target 'Core' from project 'BuildkiteTestCollector')
  |  
  | Command CompileSwift failed with a nonzero exit code
  | ^
  |  
  |  
  | ▸ Compiling UploadClient.swift
  |  
  | ❌  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/SourcePackages/checkouts/test-collector-swift/Sources/Core/Tracer/Tracer+Live.swift:32:38: cannot assign value of type 'Double?' to type 'TimeInterval' (aka 'Double')
  |  
  | span.duration = span.startAt.map { endAt - $0 }
  | ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  |  
  |  
  |  
  | ❌  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/SourcePackages/checkouts/test-collector-swift/Sources/Core/Tracer/Tracer+Live.swift:19:88: missing argument for parameter 'duration' in call
  |  
  | let span = Trace.Span(section: section, startAt: systemUptime(), detail: detail)
  | ^
  |  
  |  
  |  
  | ⚠️  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/Build/Intermediates.noindex/BuildkiteTestCollector.build/Debug-iphonesimulator/Core.build/Objects-normal/x86_64/UploadClient.dia:1:1: Could not read serialized diagnostics file: error("Invalid diagnostics signature") (in target 'Core' from project 'BuildkiteTestCollector')
  |  
  | Command CompileSwift failed with a nonzero exit code
  | ^
  |  
  |  
  | ▸ Compiling DispatchGroup.swift
  |  
  | ❌  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/SourcePackages/checkouts/test-collector-swift/Sources/Core/Tracer/Tracer+Live.swift:32:38: cannot assign value of type 'Double?' to type 'TimeInterval' (aka 'Double')
  |  
  | span.duration = span.startAt.map { endAt - $0 }
  | ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  |  
  |  
  |  
  | ❌  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/SourcePackages/checkouts/test-collector-swift/Sources/Core/Tracer/Tracer+Live.swift:19:88: missing argument for parameter 'duration' in call
  |  
  | let span = Trace.Span(section: section, startAt: systemUptime(), detail: detail)
  | ^
  |  
  |  
  |  
  | ⚠️  /usr/local/var/buildkite-agent/builds/builder/automattic/tracks-ios/.build/derived-data/Build/Intermediates.noindex/BuildkiteTestCollector.build/Debug-iphonesimulator/Core.build/Objects-normal/x86_64/DispatchGroup.dia:1:1: Could not read serialized diagnostics file: error("Invalid diagnostics signature") (in target 'Core' from project 'BuildkiteTestCollector')
```

I get the same errors when trying on my local machine.

**Comment by mokagio** [comment]
> Also, would love to get your feedback on the collector after you've had a chance to test it out :)

I'm just going through the setup steps. I haven't been able to see any analytics yet 🤔 Even when using version 0.1.0 with the [appropriate name](https://github.com/Automattic/Automattic-Tracks-iOS/pull/205/commits/d553f176505f1ae5d9ad6d54b35f492bca82695f), I don't see any results coming through in the tests analytics UI. That is, it still shows the "Complete setup" flow.

One thing I noticed is that the examples in the repo use `swift test`. So far, I tried to include it in the WordPress iOS repo, using SPM from Xcode, and the repo linked above, which is an internal library. Neither of them uses `swift` to run the tests, actually, both use Fastlane, which uses `xcodebuild` under the hood. I'm pointing this out in case `swift test` is the only supported way in which the integration works.

**Comment by iampatbrown** [comment]
@mokagio I'll fix that asap. That was a mistake on my end :) It should work fine with xcodebuild I believe `0.1.0` had an old endpoint as well. I'll get back yo you in more detail shortly. Wan't to fix the duration bug quickly.

**Comment by iampatbrown** [comment]
@mokagio I re-released it as [v0.1.1](https://github.com/buildkite/test-collector-swift/releases/tag/v0.1.1). Sorry about that. I had included a change from a dev branch unintentionally.

**Comment by mokagio** [comment]
No worries. I'll try it out right now 👍

**Comment by mokagio** [comment]
@iampatbrown Happy to report that the fixed 0.1.1 version resulted in a green build... and I now have access to the Test Analytics 🎉 

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/1218433/173742115-741cc133-a7ad-43cc-b2a4-17550c5dd8c0.png">

**Comment by mokagio** [comment]
I wonder why it didn't work before with version 0.1.0? 🤔 

I'm going to be trying on WordPress iOS between today and tomorrow. WordPress iOS uses Nimble here and there, which should answer the question from #12.

As far as I'm concerned, this issue can be closed. Thanks again 🙇‍♂️

**Comment by iampatbrown** [comment]
Regarding `swift test` and `xcodebuild` both should work. I have been using GitHub workflows during development and would test across all platforms. [Here is a workflow ](https://github.com/iampatbrown/test-collector-swift/blob/e5eefcf401257b87a4ba12282d1af28a8d935d75/.github/workflows/ci-macos-platforms.yml#L53-L55 )that uses `xcodebuild`. I haven't tested with Fastlane myself, but will look at setting something up. 

The plan is to use Buildkite pipelines (see [Configure Buildkite pipelines (#2)](https://github.com/buildkite/test-collector-swift/issues/2)) for the main branch as well as provide more comprehensive examples. We didn't have enough time to get this set up before launch but it's in the works. 

There is also a bit undocumented/wip so if you have anymore questions just ask and I can help fill in the gaps :)

**Comment by iampatbrown** [comment]
@mokagio Awesome thanks for your patience :) 

I noticed you were using it with an `ObjC` test target. I never actually tested this myself. I'll make a note to add an `ObjC` test case/example as well.

Let me know if there are any more issues.

Thanks for giving it a test drive! :)
