### ISSUE TITLE
Analytics currently not being reported

### ISSUE THREAD

**Issue by mokagio** [buildkite/test-collector-swift#25]
## 🌎 Environment

- collector-swift version: 0.1.1
- Xcode: 13.4.1
- Swift: iOS 15.5

## 💬 Description

I'm no longer seeing test analytics reports for my builds. At first, I thought it was an issue with UI tests, but I've been able to reproduce it in isolation by re-building a build that previously had reported its results and saw that it did not 🤔 

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/1218433/178164603-2bbea669-994b-472a-852f-6e113f0bc63f.png">

- [First run, with analytics](https://buildkite.com/automattic/testpress-apple/builds/25)
- [Second run, no analytics](https://buildkite.com/automattic/testpress-apple/builds/40)

## 🦶 Reproduction Steps

See this PR with logs enabled and its [build](https://buildkite.com/automattic/testpress-apple/builds/38#0181ea25-c596-47cc-a742-5dad30c1536c/673-771). In particular, the logs say

```
[22:09:25]: ▸ [BuildkiteTestCollector] debug: uploading TestResults(format: "json", runEnv: Core.RunEnvironment(ci: Optional("buildkite"), key: "0181ea25-9d34-4aa7-b5e4-f2cffcbc7cfa", url: Optional(""), branch: Optional("all-env-vars"), commitSha: Optional("a4dcee506f20bc8bbbfd9e35c5cc7d7a9f88402e"), number: Optional(""), jobId: Optional("0181ea25-c596-47cc-a742-5dad30c1536c"), message: Optional(""), debug: Optional("true"), version: Optional("0.1.1"), collector: Optional("test-collector-swift")), data: [Core.Trace(id: "C2E956C2-032E-4C2E-AF1F-680B870347EA", scope: Optional("TestPressTests"), name: Optional("testExample"), identifier: Optional("TestPressTests.testExample"), location: nil, fileName: nil, result: Optional(Core.Trace.Result.passed), failureReason: nil, failureExpanded: [], history: Core.Trace.Span(section: "top", startAt: Optional(162.64868734200002), endAt: Optional(162.651008788), duration: Optional(0.0023214459999962855), detail: [:], children: []))])

[22:09:26]: ▸ 2022-07-10 22:09:26.317657+0000 TestPress[1267:9009] [boringssl] boringssl_metrics_log_metric_block_invoke(153) Failed to log metrics

[22:09:26]: ▸ [BuildkiteTestCollector] error: The data couldn’t be read because it is missing.
```

I'm quite sure nothing changed on the CI environment on our end. Is it possible that something changed in the Buildkite Test Analytics API the test collector uses?

---

Update: Regarding the timeline, the latest build with analytics I could find in our system run on Fri 8th Jul 2022 at 23:34 UTC

![image](https://user-images.githubusercontent.com/1218433/178165199-626e0636-554b-4297-8579-28ee821bc741.png)

<img width="672" alt="image" src="https://user-images.githubusercontent.com/1218433/178166786-cf7cdff8-9cb7-4227-a91a-8833e74dcab5.png">

**Comment by iampatbrown** [comment]
@mokagio I'll chase this up today. 

> Is it possible that something changed in the Buildkite Test Analytics API the test collector uses?

That sounds most likely. We haven't made any changes to the Swift collector. This renews my interest in implementing a method for capturing the analytics to file. In event's like this it could be useful.

Out of curiosity, if the Api were ever down or something occurred that impacted an upload, would missing analytics cause problems and would backfilling be something that you'd need?

> See this PR with logs enabled and its [build](https://buildkite.com/automattic/testpress-apple/builds/38#0181ea25-c596-47cc-a742-5dad30c1536c/673-771). In particular, the logs say:

I don't have access to your Buildkite account, but the logs look like something on the Api end. It's probably worth improving the error messaging on the Swift collector. I'll look into this too.

I'll get back to you soon :)

**Comment by mokagio** [comment]
Thank you @iampatbrown , helpful as always.

> Out of curiosity, if the Api were ever down or something occurred that impacted an upload, would missing analytics cause problems and would backfilling be something that you'd need?

At this point in time, I wouldn't feel the need for backfilling. Analytics down is a "problem" in that the more data we have the better the analytics are, but the system is not mission critical for us.

**Comment by iampatbrown** [comment]
@mokagio now that we've merged #27 want to give it another try against `main` and let us know the results?

**Comment by mokagio** [comment]
@iampatbrown Now that the error logging is more informative, everything makes sense!

```
[20:31:44]: ▸ [BuildkiteTestCollector] error: You have exceeded the number of executions available on the free plan. Please upgrade to a paid plan to continue processing test executions.
```

![image](https://user-images.githubusercontent.com/1218433/178372919-d7fa872e-798f-4895-8ead-ee48645645cc.png)

_For the record, I'm not using analytics from the free plan but from a legacy one._

The error is consistent with the Test Analytics UI showing a notice about exceeded quotas:

![image](https://user-images.githubusercontent.com/1218433/178373315-a65a6f35-8725-4c15-9feb-ade6661473f3.png)

It might have been there all along and I missed it 😳 . In my defense, the problem the way I saw it was that there was no link to Test Analytics in the Buildkite builds, which is why I didn't spend much time on the Test Analytics pages.

Anyways, _all's well what ends well_ and I'm glad this resulted in an improvement in the library 😄 

As suggestion: It would be useful to have the notice about the Test Analytics quota being reached appear in the Buildkite build UI as well.

**Comment by mokagio** [comment]
As far as I'm concerned, this can now be closed.
