### ISSUE TITLE
URL, build number, and commit message possibly not forwarded from test runner environment to `EnvironmentValues`

### ISSUE THREAD

**Issue by mokagio** [buildkite/test-collector-swift#26]
## 🌎 Environment

- collector-swift version: 
- Xcode: 
- Swift: 
- OS: 

## 💬 Description

I noticed the backlink to the Buildkite build from a Test Analytics test run page doesn't work. In the screenshot below, you can see the `a` doesn't have the `href` attribute and the text is "Build #" which makes me think there should be a number after the "#":

![image](https://user-images.githubusercontent.com/1218433/178189441-f94f9ff1-a995-4761-97c2-aeb5da14f18a.png)

Looking at the logs ([via this PR](https://github.com/Automattic/TestPress-Apple/pull/6)) I noticed that the `url`, `number`, and `message` parameters are empty string. This is consistent with the UI not having a backlink or a build number to show:

```
[22:09:25]: ▸ [BuildkiteTestCollector] debug: uploading

TestResults(
  format: "json",
  runEnv: Core.RunEnvironment(
    ci: Optional("buildkite"),
    key: "0181ea25-9d34-4aa7-b5e4-f2cffcbc7cfa",
👉  url: Optional(""),
    branch: Optional("all-env-vars"),
    commitSha: Optional("a4dcee506f20bc8bbbfd9e35c5cc7d7a9f88402e"),
👉  number: Optional(""),
    jobId: Optional("0181ea25-c596-47cc-a742-5dad30c1536c"),
👉  message: Optional(""), 
    debug: Optional("true"),
    version: Optional("0.1.1"),
    collector: Optional("test-collector-swift")
  ), 
  data: ...
```

## 🦶 Reproduction Steps

Run a build on https://github.com/Automattic/TestPress-Apple/pull/6.

---

☝️ It's totally possible that I misconfigured something in how I forward the environment variables. Although, I double checked and it all seems to match:

<img width="2382" alt="test-collector" src="https://user-images.githubusercontent.com/1218433/178190565-9e48334f-f68a-4f31-9c58-115b714d4520.png">

**Comment by JamesW-iOS** [comment]
Hi @mokagio, I've just started helping out with the library with @iampatbrown. Bit of a weird one there, from an initial look it seems to be configured correctly. I'll keep digging though. I tried copying your test plan variables into personal project I've been using to test and everything seems to get passed through🧐.

I can't imagine it would make a difference but perhaps try changing 'Target For Variable Expansion' from `TestPressTests` too `TestPress`. It's the only thing I can see different at this stage.

**Comment by mokagio** [comment]
Hey @JamesW-iOS nice to meet you 👋 ☺️

I'll give your suggestion a shot. 👍

**Comment by mokagio** [comment]
> I'll give your suggestion [to change the `targetForVariableExpansion`] a shot. 👍

I tried it [here](https://github.com/Automattic/TestPress-Apple/commit/d9fe98c20a90f1668c2670762903b2486f17ba54) but the result was the same.

**Comment by mokagio** [comment]
@JamesW-iOS brilliant!

The fact that it works for you made me take a few steps back and remember something about our VMs management setup. 

Turns out [we don't forward those three environment variables to the VMs we instantiate](https://github.com/Automattic/hostmgr/blob/b8ae9528a6469022c59341998f661ddb4d52a292/Sources/hostmgr/commands/generate/GenerateBuildkiteJobScript.swift#L33-L68) 🤦‍♂️ 

We can safely close this. Thank you for digging into this and sorry for the wasted time.

**Comment by iampatbrown** [comment]
Solid work @mokagio and @JamesW-iOS 👏

**Comment by JamesW-iOS** [comment]
@mokagio Glad to hear, no stress happy we got to the bottom of it
