### ISSUE TITLE
Expose API endpoint so clients can add it to allow-lists when stubbing network requests

### ISSUE THREAD

**Issue by mokagio** [buildkite/test-collector-swift#36]
## 💬  Context

I recently [added](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/530) Test Analytics to a project that uses OHHTTPStubs to stub certain network requests when running unit tests.

One particular test had a blanket stub that run for all requests initiated in that test. The test started to fail because the test suite was making unexpected HTTP calls to the Test Analytics REST API. To make the test green again, I [updated the stub definition so allow requests to Test Analytics](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/530/files#diff-afba99c49195ec1e8df0db9bb9db48334885ce61d83e10494eb4d95a09969b80R134-R136). I did that based on the URL from the test failure:

`testDeleteEmailFollowerWithServerErrorFails, failed - Unexpected network request was made to: https://analytics-api.buildkite.com/v1/uploads`

To keep my tests neat, I defined the URL [in a `TestCollector` extension](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/530/files#diff-a5ac386601393cfca966d38e59ab93c44593ca5a926765a93f8aff149d743dd3).

I wonder how you'd feel about exposing the API endpoint, I'm not sure if the whole URL or just the host, so that consumers can use it for similar purposes.

## 📝 Notes
N.A.

## 👩‍🔧 Technical Design Notes
N.A.

## 🤝 Related

#7

**Comment by swebb** [comment]
Thank you @mokagio for reporting this issue. Are you suggesting we define a constant in the package that you can use to for allow lists?

**Comment by mokagio** [comment]
@swebb exactly.

I've done it in a custom `extension` in a couple of our projects, then used it together with [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs) like so:

```swift
// Stub all requests other than those to the Buildkite Test Analytics API,
// which we need them to go through for Test Analytics reporting.
stub(condition: !isHost(TestCollector.apiHost)) { request in
```

**Comment by swebb** [comment]
That makes sense. At present we're not working on the Swift test collector so we won't make this change at the moment. However, I'll leave this issue open and we can address it next time we update the collector.

**Comment by iampatbrown** [comment]
Hey @mokagio :)

Are you still using the extension approach? Do you think this would still be a useful additional to the library?

If we started using a web socket connection would that change anything on your end?

**Comment by iampatbrown** [comment]
@mokagio `"https://analytics-api.buildkite.com/v1"` is now accessible via `TestCollector.baseURL: String`. I'm hoping this gives you what you need.
