### ISSUE TITLE
Metrics showing on Buildkite Analytics and the corresponding buildkite job are inconsistent

### ISSUE THREAD

**Issue by seekasiacarrielai** [buildkite/test-collector-swift#37]
## 🌎 Environment

- collector-swift version:  0.3.0
- Xcode:  14.0.1
- Swift:  5.6
- OS: 

## 🦶 Reproduction Steps

1. Go to Buildkite Analytics test suite
2. Select a test run
3. Compare test execution count and test duration with the data from the corresponding buildkite job, the numbers are inconsistent

## 🤔 Expected Results
For example in this test run:
1. it actually ran 12236 test executions instead of 3000, and the number is not always the same while I have checked the no. of test executions in these buildkite jobs remains the same
2. the test duration displayed on Buildkite Analytics is calculated by avg test duration x test execution count = 1m 12s, but according to the buildkite job it is around 2-3 minutes.

## 📸 Screenshots
Buildkite Analytics:
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/17189768/196095864-0ef92310-5507-4636-8406-9e685ca0fcde.png">
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/17189768/196097097-b2d93a85-c13c-4e34-aab6-8534a967f025.png">

Buildkite job:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/17189768/196096330-35643820-0380-4cba-8530-a32f5e78df33.png">

## 🤝 Related

- Related PR, issue or link: #xxx, #yyy, https://...

**Comment by meiqimichelle** [comment]
Thanks for this detailed bug report @seekasiacarrielai ! We've had an initial look, and are finding time to do a deeper dive. Really appreciate your report, and we hope to be able to resolve this for you soon.

**Comment by iampatbrown** [comment]
Hey @seekasiacarrielai, 

We are looking into this today and will let you know how it goes. Thanks for providing so much info.

**Comment by iampatbrown** [comment]
@seekasiacarrielai 

I'm pretty sure #39 will fix this issue. If you'd like to confirm before we merge you can use the branch from the PR [iampatbrown:fix/start-uploads-synchronously](https://github.com/iampatbrown/test-collector-swift/tree/fix/start-uploads-synchronously)

**Comment by DechengMa** [comment]
Hi @seekasiacarrielai, Just checking in - has this issue been sorted out for you? Going to close it for now, but if you're still running into problems, feel free to reopen or reach out. Thanks!
