### ISSUE TITLE
Use WebSocket api instead of REST api

### ISSUE THREAD

**Issue by iampatbrown** [buildkite/test-collector-swift#7]
## 💬  Context

Currently trace results are uploaded using the REST api. The preference is to be consistent with the rspec collector and use the WebSocket api. WebSocket is also suitable because the expectation is the connection to the api will be stable and the data flow is primarily in one direction.

## 📝 Notes

- Implement a WebSocket `UploadClient`. 
- There might be some overlap with `ApiClient` but that was build more around a REST api. 
- Is there going to be a situation in the future where REST is required? Maybe certain CI environments?

## 🤝 Related

- [rspec implementation](https://github.com/buildkite/rspec-buildkite-analytics/blob/main/lib/buildkite/collector/socket_connection.rb)

**Comment by JamesW-iOS** [comment]
Since we're not currently supporting the web socket api, I've removed the conversion function in the code base to avoid possible confusion in the future. When this feature is eventually added add this function back in the `TestResults` struct

```swift
  /// Constructs test results compatible with the WebSocket API
  ///
  /// - Parameters:
  ///   - runEnv: The run environment for when the data was captured.
  ///   - data: An array of traces.
  /// - Returns: Test results compatible with the WebSocket API
  static func webSocket(runEnv: RunEnvironment, data: [Trace]) -> TestResults {
    TestResults(format: "websocket", runEnv: runEnv, data: data)
  }
```

#34

**Comment by iampatbrown** [comment]
@JamesW-iOS Good call :) Thanks for this!

**Comment by iampatbrown** [comment]
Superseded by #44
